#!/bin/bash

# Oracle Settings
export TMP=/tmp
export TMPDIR=\$TMP

#export ORACLE_HOSTNAME=fedora31.localdomain
export ORACLE_UNQNAME=orcl 
export ORACLE_BASE=/u01/app/moein
export ORACLE_HOME=$ORACLE_BASE/product/12.2.0/dbhome_1
export ORACLE_HOME_LISTNER=$ORACLE_HOME
export ORA_INVENTORY=/u01/app/oraInvenotry
export ORACLE_SID=orcl
#export PDB_NAME=pdb1
#export DATA_DIR=/u02/data

#export PATH=/usr/sbin:/usr/local/bin:\$PATH
#export PATH=\$ORACLE_HOME/bin:\$PATH
export PATH=$ORACLE_HOME/bin:$PATH

#export LD_LIBRARY_PATH=\$ORACLE_HOME/lib:/lib:/usr/lib
export CLASSPATH=\$ORACLE_HOME/jlib:\$ORACLE_HOME/rdbms/jlib
